export const GET_ALL_SPECIALIZATION_REQUEST =
  "SPECIALIZATION.GET_ALL_SPECIALIZATION_REQUEST";
export const GET_ALL_SPECIALIZATION_SUCCESS =
  "SPECIALIZATION.GET_ALL_SPECIALIZATION_SUCCESS";
export const GET_ALL_SPECIALIZATION_FAILURE =
  "SPECIALIZATION.GET_ALL_SPECIALIZATION_FAILURE";
