import logo from "./logo.svg";
import "bootstrap/dist/css/bootstrap.min.css";
import "./App.css";
import { BrowserRouter as Router } from "react-router-dom";

import Routes from "./routes";
import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faAngry,
  faLaugh,
  faSadCry,
  faThumbsUp,
  faHeart,
  faPlus,
  faTrashAlt,
  faEdit,
  faChevronLeft,
  faSort,
  faCheckSquare,
  faCheckCircle,
  faTimesCircle,
  faPauseCircle,
  faCircle,
  faUser,
  faMinusCircle,
  faRegistered,
  faChartLine,
  faSignOutAlt,
  faSignInAlt,
  faUsers,
  faCalendar,
  faUserFriends,
  faFlag,
  faAngleDown,
  faCaretDown,
  faCog,
  faBell,
  faVideo,
  faPhotoVideo,
  faComment,
  faShare,
  faSmile,
  faShoppingCart,
  faSearch,
  faChevronRight,
  faMapMarkedAlt,
  faMobileAlt,
  faEnvelope,
  faUserCircle,
  faUniversity,
  faUserGraduate,
  faBirthdayCake,
  faStar,
  faAngleDoubleUp,
  faExclamationTriangle,
  faUpload,
  faArrowRight,
  faInfoCircle,
  faUserMd,
  faCalendarWeek,
  faEye,
  faToggleOn,
  faToggleOff,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAngry,
  faLaugh,
  faSadCry,
  faThumbsUp,
  faHeart,
  faPlus,
  faTrashAlt,
  faEdit,
  faChevronLeft,
  faSort,
  faCheckSquare,
  faCheckCircle,
  faTimesCircle,
  faPauseCircle,
  faCircle,
  faMinusCircle,
  faUser,
  faRegistered,
  faChartLine,
  faSignOutAlt,
  faSignInAlt,
  faUsers,
  faCalendar,
  faUserFriends,
  faFlag,
  faAngleDown,
  faCaretDown,
  faCog,
  faBell,
  faVideo,
  faPhotoVideo,
  faComment,
  faShare,
  faSmile,
  faShoppingCart,
  faSearch,
  faChevronRight,
  faMapMarkedAlt,
  faMobileAlt,
  faEnvelope,
  faUserCircle,
  faUniversity,
  faUserGraduate,
  faBirthdayCake,
  faStar,
  faAngleDoubleUp,
  faExclamationTriangle,
  faUpload,
  faArrowRight,
  faInfoCircle,
  faUserMd,
  faCalendarWeek,
  faEye,
  faToggleOn,
  faToggleOff
);

function App() {
  return (
    <Router>
      <Routes />
    </Router>
  );
}

export default App;
